### ISSUE TITLE
Problems and a suggestion

### ISSUE THREAD

**Issue by xitero** [sleeyax/stremio-discord#2] opened 2020-01-25 05:44 UTC
- In some cases it does not show on Discord the content I am watching for example TV series or IPTV, it just shows that Stremio is open (I have not identified a pattern for this).

- After some time of use this extension and switching to different TV series or whatever, Discord stops showing what content is being watched and just says that Stremio is open.

- When opening an episode, the "time left" starts to run with the episode still loading, that is, not having started yet.

When opening an episode that is already in progress (for example, if I watched a few minutes of that episode before), the "time left" on Discord shows the count as if the episode was at the beginning and not at the moment it is.

- Time left continues to run even with the episode paused.
![image](https://user-images.githubusercontent.com/28655175/73110872-c400ac00-3ee6-11ea-9f52-5125715877ce.png)
![image](https://user-images.githubusercontent.com/28655175/73110876-c8c56000-3ee6-11ea-81b1-23296436048d.png)

- When switching from one episode to another of the same TV series, the "time left" does not reset.

- If I was watching something, even if I close the episode or when the episode ends, the name and "time left" of what I was watching will still appear until the countdown ends or until I open a different content (like another tv series/movie). Even after closing Stremio on the taskbar icons or in the task manager, it still appears on Discord that I have Stremio open and what I was watching. In order not to appear in Discord that Stremio is open, it is not enough to close it, it is necessary to restart PimpMyStremio or Discord.

Note: The problems occurs with all content, I used TV series as an example.

There may be other problems that I am not remembering right now, but I believe that they are all caused by not having a real-time tracking.

And here's a suggestion to also show which season and episode is being watched, the name of the episode would also be cool. I even believe that it would also fix the problem that when switching from one episode to another of the same TV series, the "time left" does not reset.

**Comment by sleeyax** [comment] 2020-01-25 11:13
The problem is that real time tracking is not possible because Stremio doesn't provide any information about the current state of the player to the addon. If only I could get my hands on a timestamp and current show while it's playing this wouldn't be an issue.

So, as a work around this addon uses the subtitles handler of the [addon SDK](https://github.com/Stremio/stremio-addon-sdk) to capture the IMDBID of the playing show. To show the duraton it scrapes it from the IMDB website. The issues you're having happen when the subtitles either don't load or are already loaded.

I know this isn't perfect, but it's the only 'official' way to have a discord addon right now.

**Comment by sleeyax** [comment] 2020-09-12 11:37
Closing because not fixable due to Stremio limitations. See my previous comment for details.

**Closed by sleeyax** 2020-09-12 11:37 UTC
